---
title: "Weather Prediction"
output:
  pdf_document: default
  html_document: default
date: "`r Sys.Date()`"
---

```{r}
#Read the data 
library(dplyr)
library(plyr)
data<-read.csv("weather.csv")
head(data)
```

Changing boolean values to 0,1
```{r}
#data$RainToday <- revalue(data$RainToday, c("Yes"=1))
#data$RainTomorrow <- revalue(data$RainTomorrow, c("Yes"=1))
#data$RainToday <- revalue(data$RainToday, c("No"=0))
#data$RainTomorrow <- revalue(data$RainTomorrow, c("No"=0))
data$RainToday=as.factor(data$RainToday)
data$RainTomorrow=as.factor(data$RainTomorrow)
head(data)
```


Remove missing values
```{r}
data=na.omit(data)
```
SPLITTING THE DATA
```{r}
library(caret)
index <- sample(c(TRUE, FALSE), nrow(data), replace=TRUE, prob=c(0.80,0.20))
trainData<-data[index,]
testData<-data[!index,]
dim(trainData)
dim(testData)
```
BUILDING THE DECISION TREE MODEL
```{r}
library(rpart)
library(rpart.plot)
```

```{r}
model=rpart(RainTomorrow~.,trainData)
rpart.plot(model)
```
```{r}

Prediction <- predict(model, testData, type= "class")
confusionMatrix(Prediction, testData$RainTomorrow, positive= "Yes")

```
The Accuracy of the model is 87.7%
